gtri/scrimmage

include/scrimmage/plugins/sensor/NoisyContacts/NoisyContacts.h, include/scrimmage/plugins/sensor/NoisyState/NoisyState.h, include/scrimmage/plugins/sensor/SimpleCamera/SimpleCamera.h, include/scrimmage/sensor/Sensor.h, src/plugins/autonomy/Straight/Straight.cpp, src/plugins/sensor/CMakeLists.txt, src/plugins/sensor/NoisyContacts/NoisyContacts.cpp, src/plugins/sensor/NoisyState/NoisyState.cpp, src/plugins/sensor/SimpleCamera/SimpleCamera.cpp, src/simcontrol/SimControl.cpp, test/test_sensor.cpp
1) changes the signature to use boost::optional instead of updating a
reference to valid
2) adds enable_if to Sensor class so that users do not need to specify
sense<sc::Message<data_type>>. They can now just do sense<data_type>
3) enabled SimpleCamera
4) add test for SimpleCamera
=> update to new sensor interface

include/scrimmage/plugin_manager/Plugin.h
Didn't see this error on Travis, but I had a local compile error due to unordered_map not being included in Plugin.h. Adding that include fixed it for me.
=> include unordered_map to fix compile err

include/scrimmage/plugins/metrics/SimpleCollisionMetrics/SimpleCollisionMetrics.h, src/plugins/metrics/SimpleCollisionMetrics/SimpleCollisionMetrics.cpp
This is a new attempt of my previous pull request after rebasing on the latest master. Assuming travis approves this one, the previous PR is redundant/outdated.
=> Initialize scores, rearrange a bit for flight time calc

include/scrimmage/math/Angles.h, src/log/FrameUpdateClient.cpp, src/math/Angles.cpp, src/plugins/autonomy/ArduPilot/ArduPilot.cpp, src/plugins/autonomy/MultirotorTests/MultirotorTests.cpp, src/plugins/motion/JSBSimModel/JSBSimModel.cpp, test/test_angles.cpp
it is common to use the ``Angles`` class to convert between gps and euclidean coordinates. This pull request adds a constructor to that class to faciliate this initialization.
=> make gps/euclidean conversions easier

include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.h, include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.xml, include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCameraNoNoise.xml, include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCameraType.h, src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp
ContactBlobCamera sensor plugin now considers false positives and false negatives.
- **False negatives**:
User specifies the false negative probability. For each detection, the plugin generates a random number between 0 and 1. If it's less than the set probability, then the detected bounding box is skipped to simulate a false negative.
- **False positives**:
User specifies the false positive probability and the maximum number of false positives (N) any given frame can have. For each detection, the plugin generates N random numbers between 0 and 1. The instances that yield a value less than the set probability will be considered as a false positive. For the current frame, a bounding box will be added centered at random pixel coordinates.
=> More realistic ContactBlobCamera sensor plugin

share/scrimmage/CMakeLists.txt, test/CMakeLists.txt, tools/aggregate-runs/CMakeLists.txt, tools/filter-runs/CMakeLists.txt, tools/scrimmage-plugin/CMakeLists.txt
Fixed an issue with previous merge that would cause cmake errors when python was disabled. This error didn't appear before because target_link_libraries() does not throw an error when linked against an empty string, which would have instead potentially caused cryptic errors at runtime. Now scrimmage will never link to empty library strings.
=> fix linking errors when python is disabled

src/plugins/metrics/CPA/CPA.cpp
Fixed error with a Segfault happening in CPA.cpp - in the case that an entity was destroyed, we were still attempting to access their state which was a shared pointer to empty
=> Fixed segfault from CPA.cpp

include/scrimmage/parse/ConfigParse.h, include/scrimmage/plugins/autonomy/BoundaryDefense/BoundaryDefense.h, include/scrimmage/plugins/autonomy/CommandStringRelay/CommandStringRelay.h, include/scrimmage/plugins/autonomy/TakeFlag/TakeFlag.h, include/scrimmage/plugins/controller/UUV6DOFPIDController/UUV6DOFPIDController.h, include/scrimmage/plugins/interaction/Boundary/BoundaryInfo.h, include/scrimmage/plugins/interaction/GRPCCommandString/GRPCCommandString.h, src/parse/ConfigParse.cpp, src/plugins/autonomy/BoundaryDefense/BoundaryDefense.cpp, src/plugins/autonomy/TakeFlag/TakeFlag.cpp, src/plugins/controller/UUV6DOFPIDController/UUV6DOFPIDController.cpp, src/plugins/interaction/Boundary/Boundary.cpp, src/plugins/interaction/GRPCCommandString/GRPCCommandString.cpp, src/plugins/interaction/SimpleCollision/SimpleCollision.cpp, src/plugins/motion/JSBSimModel/FGOutputFGMod.cpp, tools/aggregate-runs/main.cpp, tools/filter-runs/main.cpp, tools/scrimmage-plugin/main.cpp
* remove "namespace sc = sci" in headers
* use forward declarations
* put variables in reduced scope
* use const references for object passing
* use override instead of virtual
* remove use of macro for min
=> style updates

src/CMakeLists.txt
Added Eigen include dirs as interface include directories for
scrimmage-core in the install tree. This will fix potential
\#include errors for Eigen when scrimmage has been installed
to a nonstandard location.
=> add eigen include dirs to install tree

msgs/CMakeLists.txt, src/proto/CMakeLists.txt
Should be ready to go, just protobuf headers missing from install tree.
@crichardson332
=> Fixed missing proto includes in install tree

src/simcontrol/SimControl.cpp
Sensor drawn shapes weren't disappearing in the viewer after draw_shape() even with persistent set to false and a small TTL set.
Introduced by https://github.com/gtri/scrimmage/commit/b294986148b42cc6d79c5e8e84702c41de229870 which allowed sensors to display shapes in the viewer.
=> Fix sensor shapes not disappearing

src/entity/External.cpp
Added code to call the step function of sensor plugins when using the external class.
=> Allow External to step through sensor plugins

src/plugins/sensor/NoisyState/NoisyState.cpp
Refactor of noisy state sensor left out an underscore causing the xml params of form "pos_noise_0" to not be read properly.
=> Fix missing underscore noisy state

include/scrimmage/plugins/network/SphereNetwork/SphereNetwork.h, include/scrimmage/plugins/network/SphereNetwork/SphereNetwork.xml, src/plugins/network/SphereNetwork/SphereNetwork.cpp, src/simcontrol/SimUtils.cpp
There is now an option to add a planar boundary to the sphere network.
A use case example is to model underwater communications not being able
to go beyond the surface of the water to aerial vehicles and vice versa.
=> Added planar boundary in SphereNetwork.

msgs/CMakeLists.txt, src/plugins/autonomy/BoundaryDefense/CMakeLists.txt
- fix a bug in proto path in /msgs for non-GRPC build
- add compiler flag to BoundaryDefense plugin that causes
build failure on some systems
=> fix bug in msgs cmake

include/scrimmage/common/Utilities.h, include/scrimmage/entity/Entity.h, include/scrimmage/entity/External.h, include/scrimmage/parse/MissionParse.h, include/scrimmage/parse/ParseUtils.h, include/scrimmage/plugin_manager/PluginManager.h, include/scrimmage/simcontrol/SimUtils.h, missions/auction_assign.xml, missions/auction_assign2.xml, missions/fsm-motor-schemas.xml, missions/uuv-ex1.xml, src/common/Utilities.cpp, src/entity/Entity.cpp, src/entity/External.cpp, src/parse/MissionParse.cpp, src/parse/ParseUtils.cpp, src/plugin_manager/PluginManager.cpp, src/plugins/autonomy/AutonomyExecutor/AutonomyExecutor.cpp, src/plugins/autonomy/MotorSchemas/MotorSchemas.cpp, src/plugins/autonomy/WaypointGenerator/WaypointGenerator.cpp, src/plugins/controller/DoubleIntegratorControllerWaypoint/DoubleIntegratorControllerWaypoint.cpp, src/plugins/interaction/MapGen2D/MapGen2D.cpp, src/pubsub/Network.cpp, src/simcontrol/SimControl.cpp, src/simcontrol/SimUtils.cpp, src/viewer/Updater.cpp, src/viewer/Viewer.cpp
Eric,
I have updated the external class and plugin creation functions to use the tags attribute in all plugins to enable or disable loading of that plugin. Also, we can now override plugin parameters from a process that calls the External class' create_entity function (e.g., override scrimmage plugins with ROS parameters at initialization time).  Please take a look and let me know what you think. This commit will fail to build until I also update the scrimmage_ros package, so don't accept this merge request, but provide any feedback that you have. I will need to update the documentation for using scrimmage within a ROS nodelet as well.
=> Override parameters from external, plugin tags for external

src/plugins/autonomy/BoundaryDefense/CMakeLists.txt, src/plugins/controller/UUV6DOFLinearEnergy/CMakeLists.txt, src/plugins/controller/UnicyclePID/CMakeLists.txt, src/plugins/sensor/NoisyContacts/CMakeLists.txt
Remove fext-numeric-literals flag that was erroneously added recently, which is unavailable in clang
=> update remaining plugins with no-c-linkage flag

scripts/templates/cmake-project/CMakeLists.txt
A mismatch between the template name of a parameter for GenerateSetEnv and the actual parameter name causes no more setenv files to get written to ~/.scrimmage in projects.
=> Use the correct variable name for home directory setup in GenerateSetEnv

src/plugins/motion/UUV6DOF/UUV6DOF.cpp
There was in issue in UUV6DOF where we set a variable to exactly 0. In the motion model calculations this later caused NaNs, causing the entity to disappear. This is a simple change - in the case that the motion model put the UUV above the surface of the water, we had been setting it's height to the surface height. Now instead we set it to std::numeric_limits<double>::epsilon subtracted from the surface height, letting us not have an exact 0 in the case that surface_height_ is 0. 
From my test this fixed the NaN problems.
=> Fix bug in UUV6DOF

include/scrimmage/plugins/autonomy/AvoidEntityMS/AvoidEntityMS.h, src/plugins/autonomy/AvoidEntityMS/AvoidEntityMS.cpp
Optionally draw the Avoidance vector in red when using AvoidEntityMS from MotorSchemas
=> Drawing avoidance vector for AvoidEntityMS

scripts/templates/cmake-project/missions/example.xml, scripts/templates/cmake-project/msgs/CMakeLists.txt
This commit fixes build issues in the generated cmake project on clang.
=> fix compiler flags for macOS in cmake proj

docs/source/overview/xml-tags.rst
Fixed a typo: "volkswagon" to "volkswagen"
=> volkswagen typo

include/scrimmage/entity/External.h, src/entity/External.cpp
Manage a queue of shapes and prevent it from growing unbounded.
Defaults to a value of 0 which disables shape drawing (a good default for external).
Setting it to anything greater than 0, ie `external_->shape_queue_max_size() = 100` will enable shape drawing when running through external.
@SyllogismRXS
=> Add shape queue to external

include/scrimmage/plugins/interaction/RandomAttrit/RandomAttrit.h, include/scrimmage/plugins/interaction/RandomAttrit/RandomAttrit.xml, missions/random-attrit-test.xml, src/plugins/interaction/RandomAttrit/CMakeLists.txt, src/plugins/interaction/RandomAttrit/RandomAttrit.cpp
Bare bones attrition plugin. A user specifies the time at which entity removal should start, how long it should last, a team, and any entities that should be "saved" from the removal, and the plugin will remove entities until down to the "leave_alive" entities.
Every time an entity gets removed, this publishes a message containing a pointer to the entity about to be removed.
=> Add simple attrition plugin that removes entities from a team over time

src/plugins/network/LocalNetwork/LocalNetwork.cpp, src/plugins/network/SphereNetwork/SphereNetwork.cpp
At least in the case when entities collide and are set inactive, pub/sub plugins in the pubsub map in SimControl have their parent entity closed, but they stay in the pubsub map. This causes a null pointer deref when something tries to refer to the parent object of the one of these publisher or subscribers.
=> Patch segfaulting when losing entities on sphere network

include/scrimmage/entity/External.h, src/entity/External.cpp, src/parse/MissionParse.cpp
Added checks for xml parsing errors in MissionParse. However, note that sometimes it hard crashes, sometimes not.
Fixed sub_cb return that was getting bad data from a bad lambda.
Added error checking in the External step function, to catch the case where scrimmage was not setup properly. Also found a missing mutex unlock.
=> Added various error checks in MissionParse and External.

include/scrimmage/plugins/autonomy/SimpleINS/SimpleINS.h, src/plugins/autonomy/SimpleINS/SimpleINS.cpp
- Update SimpleINS autonomy to use a time variable to reset the covariance matrix to an identity matrix rather than linearly decreasing until it got near the identity matrix.
=> Update SimpleINS to use a timer in order to update covariance

CMakeLists.txt
when vtk wasn't found, cmake would throw the following
CMake Error at CMakeLists.txt:192 (if):
if given arguments:
"LESS" "7"
Unknown arguments specified
=> fix vtk7 check

src/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.cpp
Bugs fixed include nonexistent symbol kill_grpc_server() being called when built with ENABLE_GRPC=0 and accidentally killing all process ids when the variable python_cmd_ is not initialized.
=> Fix bugs in nonlearning grpc mode

include/scrimmage/math/State.h, include/scrimmage/viewer/Updater.h, python/scrimmage/bindings/src/py_math.cpp, src/math/State.cpp, src/math/StateWithCovariance.cpp, src/plugins/autonomy/Boids/Boids.cpp, src/plugins/autonomy/TrajectoryRecordPlayback/TrajectoryRecordPlayback.cpp, src/plugins/interaction/CaptureInBoundaryInteraction/CaptureInBoundaryInteraction.cpp, src/plugins/motion/FixedWing6DOF/FixedWing6DOF.cpp, src/plugins/motion/Multirotor/Multirotor.cpp, src/plugins/motion/UUV6DOF/UUV6DOF.cpp, src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp, src/proto_conversions/ProtoConversions.cpp, src/viewer/Updater.cpp
Hey guys, I wanted to suggest the idea of refactoring the getters/setters for the State class (and potentially any other class where it's relevant). The current API has 3 different methods for accessing pos/vel/etc - 1 getter, 1 setter, and 1 that can do both. This has caused me confusion and led to some very time consuming bugs related to erroneously mixing return by copy and return by reference. I've also had a few instances where I made extensive use of 'pos()' as a getter, which worked fine for a time until I ran into a situation where my object was now const. Then every instance of 'pos()' had to be changed to 'pos_const()'.
I believe these headaches can all be avoided by replacing the 3 current function calls with just 1, utilizing const overloads that the compiler will resolve for …
=> clean up const functions in State

include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.h, include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.xml, include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCameraNoNoise.xml, src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp
Added two optional features to the ContactBlobCamera sensor plugin.
show_frustum flag: visualize the frustum
log_detections flag: log the time and any detected entity ids every timestep into a sensor log in the logdir.
=> Draw ContactBlobCamera's frustum and log any detections

include/scrimmage/entity/External.h, src/entity/External.cpp
External requires a time as an input to its step function, but it also refers to rostime internally.
This makes the interface more consistent, letting external only use the time passed in through step.
=> Cleanup external's use of time

include/scrimmage/plugins/autonomy/MotorSchemas/MotorSchemas.h, src/plugins/autonomy/MotorSchemas/MotorSchemas.cpp
The Motor Schemas autonomy plugin publishes the desired heading, speed, and altitude. This commit allows the plugin to also publish the resulting velocity vector. An example use case is so that it can interact with the Single Integrator motion model.
=> allow Motor Schemas to publish the resulting velocity vector as well

include/scrimmage/plugins/autonomy/MotorSchemas/MotorSchemas.h, include/scrimmage/plugins/autonomy/MotorSchemas/MotorSchemas.xml, include/scrimmage/plugins/motion/SingleIntegrator/SingleIntegrator.h, include/scrimmage/plugins/motion/SingleIntegrator/SingleIntegrator.xml, src/plugins/autonomy/MotorSchemas/MotorSchemas.cpp, src/plugins/motion/SingleIntegrator/SingleIntegrator.cpp
The yaw value in the SingleIntegration motion plugin is currently computed as a function of the velocity vector. However, there are uses cases where the user might want to set a specific heading that is not in the direction of movement. This commit introduces the ``override_heading`` parameter. If set to true, then the heading of the vehicle will be set to whatever value is published to the ``OverrideHeading`` topic.
=> allow to override yaw value in SingleIntegrator plugin

include/scrimmage/plugins/autonomy/MoveToGoalMS/MoveToGoalMS.h, include/scrimmage/plugins/autonomy/MoveToGoalMS/MoveToGoalMS.xml, src/plugins/autonomy/MoveToGoalMS/MoveToGoalMS.cpp
The MoveToGoalMS plugin computes a velocity vector towards the waypoint goal, but it's not scaled by any speed factor. This commit adds a PID controllers that scales the magnitude of the vector as a function of the distance between the agent and the waypoint goal - i.e. the closer the agent is to the goal the smaller the magnitude of the vector. The idea is to prevent the agents from overshooting the goal.
The PID and integral band gains are part of the plugin's parameters allowing developers to easily choose the best gains for their purposes.
=> Move to goal updates

src/plugin_manager/PluginManager.cpp
Verbose error message to assist in debugging possible missing linked libraries.
=> Verbose error msg for invalid plugin dependency

include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.h, include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCameraType.h, src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp
ContactBlobCamera plugin params added to ContactBlobCameraType msg and published along with the frame and bounding boxes. Allows autonomy plugins to know camera properties like FOV, resolution, and focal length.
=> add camera params to published contact blob msg

python/completion/scrimmage-argcomplete.bash, python/scrimmage/command/util.py, python/scrimmage/scrimpy.py
- format scrimpy env consistent with env command
- add scrimpy to bash completion script
=> fix bug in calling scrimpy with no arguments

include/scrimmage/plugins/controller/JSBSimModelControllerHeadingPID/JSBSimModelControllerHeadingPID.xml, src/plugins/controller/JSBSimModelControllerHeadingPID/JSBSimModelControllerHeadingPID.cpp
The xml tag for the pid tuning is heading_pid and its values are P_gain, I_gain, D_gain, and the integral bound (in degrees).
Also fixes occasional bug where the controller would get stuck chattering due to a remapping of bank values to between -pi to pi before then also being clamped by the max bank angle
=> Add ability to tune JSBSimModelHeadingPID gains

CMakeLists.txt, ci/dockerfiles/ubuntu-16.04, docs/source/tutorials/airsim-plugin.rst, include/scrimmage/parse/ParseUtils.h, include/scrimmage/plugins/autonomy/ROSAirSim/ROSAirSim.h, include/scrimmage/plugins/autonomy/ROSAirSim/ROSAirSim.xml, include/scrimmage/plugins/autonomy/ROSAirSim/lidar.rviz, include/scrimmage/plugins/sensor/AirSimSensor/AirSimSensor.h, include/scrimmage/plugins/sensor/AirSimSensor/AirSimSensor.xml, include/scrimmage/plugins/sensor/AirSimSensor/settings.json, missions/quad-airsim-ex1.xml, src/plugins/autonomy/ROSAirSim/ROSAirSim.cpp, src/plugins/autonomy/Straight/Straight.cpp, src/plugins/sensor/AirSimSensor/AirSimSensor.cpp
Send AirSim data to ROS through scrimmage, Lidar and Images use separate scrimmage publishers, implemented ROS TF2 transform for Lidar.
=> Send AirSim Data to ROS

docs/doxyfile.in, src/plugins/autonomy/ROSAirSim/ROSAirSim.cpp, src/plugins/autonomy/Straight/Straight.cpp, src/plugins/sensor/AirSimSensor/AirSimSensor.cpp, src/plugins/sensor/ROSIMUSensor/ROSIMUSensor.cpp
Using CMAKE_SOURCE_DIRECTORY leads to incorrect input directories
if SCRIMMAGE is a git submodule. Using PROJECT_SOURCE_DIR fixes
this issue.
Fix cpplint errors
These errors occur in Ubuntu 18.04, but not in Ubuntu 16.04.
=> Use active project's root directory

missions/arducopter.xml, missions/arduplane.xml, missions/arduplane_multiple.xml
Allows ardupilot sitl to disable the gui with an additional parameter passed to sim_vehicle.py. A related merge request will be made in the Ardupilot repo to add this argument to sim_vehicle.py.
Example usage:
sim_vehicle.py -v ArduPlane -f scrimmage-plane -A"--config visual_model=cessna,motion_model=FixedWing6DOF-BlueEagle,terrain=CampAtterbury,**enable_gui=false**"
=> added optional argument of enable_gui with ardupilot SITL

src/viewer/Updater.cpp
FIxed an issue where SafeDowncast produced a nullptr and caused a segfault.
=> fixed nullptr in draw_sphere

src/simcontrol/SimControl.cpp
Due to an issue I was having with memory deallocation for (a custom/legacy project's) protobufs, I was looking to see if there was a method called by the simulator for a metrics plugin after all of the other metrics methods (`calc_team_scores`, `print_team_summaries`, etc) for all metrics plugins are called. It seemed like `close()` would do this, but I noticed in the simulator's `SimControl`, it was never called for metrics.
So, I added this to SimpleCollisionMetrics’s header file:
```
void close(double /*t*/) override { std::cout << "CALLING CLOSE IN METRICS!!!" << std::endl; }
```
No printout:
```
$ scrimmage missions/straight.xml 
[===============================================================>      ] 89 %
=============================================================================== …
```
=> close() never called for metrics plugins in SimControl::shutdown()

README.md, ci/dockerfiles/ubuntu-16.04, setup/install-binaries.sh
Just updated the installation procedures a bit to match the current arguments to the install-binaries.sh script. Also changed the way the arguments are handled by that script to handle any ordering or weird combinations users might come up with.
Replying to comments on previous PR:
- The updated script is written such that you can pass in extra arguments like -p and -e without breaking anything. As the script currently is, I don't think those flags actually do anything. I can add a check to look for those flags as well in addition to --external or --python respectively, but that would actually be introducing a change. (I stumbled on this because I was trying to install python 3 support and -p 3 was not doing anything, it was still defaulting to installing both 2 and 3 support).
- The …
=> Build Script Updates

CMakeLists.txt, README.md
Closes: #440 
Changes:
- Primarily, the main `CMakeLists.txt` was updated to remove the setting of `PYTHON_MIN_VERSION` to 2.7 by default.
- The `README.md` was updated to clarify what the `PYTHON_MIN_VERSION` flag is used for.
Functionality changes:
- `PYTHON_MIN_VERSION` was repurposed to not be set to anything by default, and instead allows the user to optionally specify, if they would prefer, a different python version to use than the environment default. For example, the latest anaconda (2020.11) comes with python 3.8.
- By default (no variables specified, e.g., `cmake ..`), CMake will use the environment default python version.
- Any previous scripts using this flag to automate the building of scrimmage should be backwards-compatible with these changes.
Testing:
```
$ cd build/
$ rm …
```
=> CMake updates to use environment Python by default

docs/source/overview/xml-tags.rst, include/scrimmage/parse/MissionParse.h, src/parse/MissionParse.cpp
Allows the user to optionally specify a top-level tag `<output_dir_trailer>`, which will append a trailing string as defined by the user to the end of the simulation's output directory's name.
Note: truncates the string to 100 characters. Replaces all occurrences of '/' with '_'.
I tested with the following tag added to Straight.xml:
```
<output_dir_trailer> [73%] Linking CXX shared library ../../../../plugin_libs/libSingleIntegratorControllerWaypointJustAddingSomeExtraCharactersHereToCauseTruncation_plugin.so</output_dir_trailer>
```
Yielding this directory:
```
$ ll
total 20
drwxrwxr-x 4 scrimmage scrimmage 4096 Feb 18 12:10  ./
drwxr-xr-x 4 scrimmage scrimmage 4096 Feb 18 11:33  ../
drwxrwxr-x 2 scrimmage scrimmage 4096 Feb 18 12:10 '2022-02-18_12-10-53_ [73%] Linking CXX shared …
```
=> Added <output_dir_trailer> tag to the XML parsing

ci/dockerfiles/centos7
Eigen can no longer be found at the link used in the Dockerfile. This commit updates the link to one that works.
=> updated eigen source

python/requirements-3.6.txt, python/requirements-3.8.txt
Replaced the packages in both `requirements-3.6.txt` and `requirements-3.8.txt`.
Installation of requirements worked fine for me in both Centos 7.9 with python 3.6.8 and Ubuntu 18.04 with anaconda3, using python 3.8.5.
See the issue for more details: https://github.com/gtri/scrimmage/issues/532
To test, follow the Python Bindings section in the main README.md
https://github.com/gtri/scrimmage#python-bindings
If you run it with the old requirements-3.6.txt, you should see an error. The error will no longer be there if you use the updated requirements-3.6.txt files from this PR.
=> Removed pkg-resources from requirements.txt and replaced it with setuptools

include/scrimmage/common/CSV.h, src/common/CSV.cpp
Closes: https://github.com/gtri/scrimmage/issues/553
CSV utility class writes doubles with some default qualities that aren't granular enough for things like lat/lon, etc.
Made some modifications to the CSV class:
- now allow the user to set precision, fixed, or scientific for writing double values out to csv files
- defaults these items to what it looked like before but with more decimal precision (see below)
Note: this should write double values similar to previously, but now with more precision than before.
- doubles in scientific notation (`double d = 3.14e-9;`) never worked (tested)
- this now provides a way to write out doubles to csv using scientific notation
- limitation: these double formatting settings will apply to any doubles you are writing to csv with the given instance …
=> Modified CSV utility to make writing doubles more configurable

python/scrimmage/proto_utils.py
Closes: https://github.com/gtri/scrimmage/issues/560
In the scrimmage python package, `python/scrimmage/proto_utils.py`, added an explicit second function called `read_frames_stream()` to take a stream as input instead of a filename. The original `read_frames()` method is still there, and still takes in a filename, but it now calls/returns `read_frames_stream()`. `read_frames_stream()` now contains the full function body that `read_frames()` used to have. 
I have basically overloaded this, but with a different function name so that anyone using this package can be pretty sure they're using the one they intended to use.
**This change should not break anything that was already using this utility package.**
Motivation: I have a post processing utility that is complex and it passes around …
=> python scrimmage/proto_utils add stream input capability

src/plugins/motion/FixedWing6DOF/FixedWing6DOF.cpp
Fixes a bug where a comparison operator was used instead of an assignment operator. Allows the moments to be zeroed during the acceleration portion of a vehicle launch.
=> in FixedWing6DOF, fix bug to zero moments during launch

include/scrimmage/parse/MissionParse.h, include/scrimmage/parse/XMLParser/LibXML2Parser.h, src/parse/MissionParse.cpp, src/parse/XMLParser/LibXML2Parser.cpp
LibXML2 parser was reading the original filecontents, not filecontents modified by the MissionParsers. This meant that any mission overrides used in files that also used xinclude were not persisted throughout the mission.
=> Minor fix to LibXML2Parser to persist Mission Overrides

src/plugins/autonomy/ArduPilot/ArduPilot.cpp
Initializes socket message flags for boost asio udp.
=> Init's Recv Flags in ArduPilot Autonomy

src/parse/MissionParse.cpp
Missing a compiler flag around a libxml member function
=> adding missing compiler flags for libxml functions

python/scrimmage/proto_utils.py, scripts/plot_3d_fr.py
Closes: https://github.com/gtri/scrimmage/issues/557
Updated `scripts/plot_3d_fr.py` - Quality of Life updates:
- ~~fixed an index error bug~~ removed this as there are bigger issues at play that need to be looked into more in-depth
- added `-i` option for interactive mode. The gui will no longer be displayed by default. If you want to run the gui, use the `-i` (interactive) flag from now on.
- made the default output directory the same directory that `frames.bin` was found in.
- added `-o` (output directory) option which will allow the user to specify an alternative output directory for writing out the plots.
Updated proto_utils.py
- make the error message in read_frames() more detailed/descriptive
These updates were made for the purpose of allowing this plotting script to be used in an …
=> Issue 557 updates to plot 3d fr py

docs/source/overview/xml-tags.rst
Adding <no_bin_logging> to documentation. No one knows that disabling bin logging (which creates massive log files) is already built into Scrimmage.
=> Updating documentation for <no_bin_logging> tag
