docs/source/overview/viewer.rst
include/scrimmage/viewer/Updater.h
src/viewer/CameraInterface.cpp
src/viewer/Updater.cpp

Added help menu overlay that displays key bindings on the screen, toggled by the 'h' key and defaulted to OFF.

Added help menu 

---

data/aircraft/Rascal/Rascalap.xml
include/scrimmage/plugins/controller/JSBSimModelControllerDirect/JSBSimModelControllerDirect.h
include/scrimmage/plugins/motion/JSBSimModel/JSBSimModel.h
include/scrimmage/plugins/motion/JSBSimModel/JSBSimModel.xml
python/scrimmage/external_control.py
src/plugins/controller/JSBSimModelControllerDirect/CMakeLists.txt
src/plugins/controller/JSBSimModelControllerDirect/JSBSimModelControllerDirect.cpp
src/plugins/motion/JSBSimModel/JSBSimModel.cpp

This adds the option to JSBSimModel to directly control the elevators and thus pitch. There is also some changes made to external_control for better usability and a unit conversion fix in JSBSimModel

JSBSimModel Pitch Control Changes

---

include/scrimmage/plugins/autonomy/ExternalControl/ExternalControl.h
python/scrimmage/external_control.py
python/setup.py.in
src/plugins/autonomy/ExternalControl/ExternalControl.cpp

Requires reinstalling SCRIMMAGE python bindings to work properly

Add option to control ExternalControl through python actor model

---

include/scrimmage/plugins/autonomy/PyAutonomy/PyAutonomy.h
missions/python-test.xml
python/scrimmage/__init__.py
python/scrimmage/bindings/src/py_autonomy.cpp
python/scrimmage/utils.py
src/plugins/autonomy/CMakeLists.txt
src/plugins/autonomy/PyAutonomy/PyAutonomy.cpp
src/plugins/autonomy/python/straight.py

The PyAutonomy plugin was updated, but the system installation of python dependencies is not automated yet.

Python autonomy fix

---

missions/capture-the-flag.xml
src/parse/MissionParse.cpp
src/plugin_manager/PluginManager.cpp
src/simcontrol/SimUtils.cpp

Eric, please test the param common block feature since this commit changes how the XML files are parsed.

Allow for multiple of same network, ent inter, metric plugin

---

setup/install-binaries.sh

Add boost graph to be installed on initial setup

Add boost_graph dependency

---

include/scrimmage/proto/ProtoConversions.h
src/proto_conversions/ProtoConversions.cpp
src/viewer/Updater.cpp

Re-added the **path_to_lines** function int the ProtoConversions.cpp class to account for some gtri-uav-scrimmage plugins that make use of it.

path_to_lines function

---

src/plugins/controller/DoubleIntegratorControllerVelYaw/DoubleIntegratorControllerVelYaw.cpp
src/plugins/motion/DoubleIntegrator/DoubleIntegrator.cpp

Fixes issues found in the Double Integrator motion model and controller.
Issues include:
* Overwriting the altitude control in the controller
* Acceleration vector created in the controller would point the direction the entity was currently pointed, not where the heading controller input indicated.
* Yaw used the derivative of vel_z, not yaw_dot to update its value.
* Acceleration and Velocity vector clamping would not maintain original direction of the vector.
* Yaw rate from controller was being used as an acceleration, not a velocity.

Update DoubleIntegrator bugs

---

include/scrimmage/plugins/autonomy/ShapeDraw/ShapeDraw.h
include/scrimmage/plugins/autonomy/ShapeDraw/ShapeDraw.xml
include/scrimmage/viewer/Updater.h
missions/shape_draw.xml
src/plugins/autonomy/ShapeDraw/CMakeLists.txt
src/plugins/autonomy/ShapeDraw/ShapeDraw.cpp
src/proto/scrimmage/proto/Shape.proto
src/viewer/Updater.cpp

Couple questions I had.
1. Do we want degrees or radians for the angle field of the ellipse?
2. Do we maybe want to do a quaternion instead? Things like the circle shape currently have no orientation, but there's no reason they couldn't right? Obviously z-axis rotation is pointless, but maybe we could want a sphere not on the xy plane at some point?

Add an ellipse shape

---

include/scrimmage/plugins/autonomy/ShapeDraw/ShapeDraw.h
include/scrimmage/viewer/Updater.h
missions/shape_draw.xml
src/plugins/autonomy/ShapeDraw/ShapeDraw.cpp
src/proto/scrimmage/proto/Shape.proto
src/viewer/Updater.cpp

Can be tested with `scrimmage missions/shape_draw.xml` A zephyr is being rendered through the shape api.

Add a shape that draws meshes

---

include/scrimmage/entity/External.h
include/scrimmage/plugins/controller/SimpleAircraftControllerPID/SimpleAircraftControllerPID.xml
src/parse/MissionParse.cpp
src/plugins/controller/SimpleAircraftControllerPID/SimpleAircraftControllerPID.cpp

Updated pub_cb to accept general callback functions while preserving current API for ROS. Also updated SimpleAircraftControllerPID to fix bugs in PIDs. Terrain offset params were also added for applying a translation to the terrain map.

Small generalizations

---

include/scrimmage/entity/Contact.h
include/scrimmage/entity/External.h
include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.h
src/entity/Contact.cpp
src/entity/Entity.cpp
src/entity/External.cpp
src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp

The three main changes in this merge request:
1. Allow to set radius of agents via the Contact class.
2. Added hooks to the ContactBlobCamera sensor plugin to allow for updating plugin parameters via the External class.
3. Allow the External class to load a single plugin instead of having to load a complete entity.

Updates to External class and ContactBlobCamera plugin

---

include/scrimmage/plugins/interaction/GraphInteraction/Graph.h
include/scrimmage/plugins/interaction/GraphInteraction/GraphInteraction.h
include/scrimmage/plugins/interaction/GraphInteraction/GraphInteraction.xml
include/scrimmage/plugins/interaction/GraphInteraction/README.md
msgs/CMakeLists.txt
msgs/Graph.proto
src/plugins/interaction/GraphInteraction/CMakeLists.txt
src/plugins/interaction/GraphInteraction/GraphInteraction.cpp

Added an entity interaction called GraphInteraction which uses graph data to visualize the graph and publish the nodes and edges. The Graph class uses the Graph msg in its constructor.
README is included alongside the header.

Add Graph Interaction

---

include/scrimmage/common/Timer.h
src/common/Timer.cpp
src/simcontrol/SimControl.cpp

Moved loop_wait call to the end of the loop, so we are waiting only for the extra time in the loop. also changed the timer interface a little

Sim timing

---

src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp

ContactBlobCamera was not using the orientation or input of the camera, so there was no way for the camera to point anywhere but straight forward.

Contact blob fix

---

src/parse/MissionParse.cpp

fixes https://github.com/gtri/scrimmage/issues/174

add warnings for redundant tags

---

scripts/generate_scenarios.py
scripts/run_experiments.py
setup/install-binaries.sh

- Add symlink to latest experiment in experiments folder
- Add ability to do a grid search over parameters (with optional count field in ranges file)
- Add ability to repeat a given set of params (can set in run_experiments.py cmdline interface)
- Add tqdm progress bar. This also provides estimated completion times for experiments.

Add Experiment Features

---

include/scrimmage/math/State.h
include/scrimmage/plugins/sensor/LOSSensor/LOSSensor.h
include/scrimmage/plugins/sensor/LOSSensor/LOSSensor.xml
msgs/LOSSensor.proto
src/plugins/sensor/LOSSensor/CMakeLists.txt
src/plugins/sensor/LOSSensor/LOSSensor.cpp

Adding LOSSensor + some code commenting to the main GTRI Scrimmage repo.

Los sensor

---

include/scrimmage/math/State.h
include/scrimmage/plugins/sensor/LOSSensor/LOSSensor.h
include/scrimmage/plugins/sensor/LOSSensor/LOSSensor.xml
src/plugins/sensor/LOSSensor/LOSSensor.cpp

Added rate controls to simulate slower LOS sensors.

Los sensor - update rate control

---

CMakeLists.txt
include/scrimmage/plugins/autonomy/RLSimple/RLSimple.xml
include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.h
include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.xml
python/scrimmage/openai_grpc_link.py
python/setup.py.in
src/CMakeLists.txt
src/plugins/autonomy/ScrimmageOpenAIAutonomy/ActorFunc.cpp
src/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.cpp
src/proto/scrimmage/proto/OpenAI.proto

Also ensures that the precompile flag ENABLE_GRPC can be seen by other
SCRIMMAGE projects through cmake

Add OpenAI nonlearning mode over grpc

---

include/scrimmage/pubsub/Network.h
include/scrimmage/pubsub/NetworkDevice.h
missions/delay-test.xml
scripts/plot_cm.py
src/entity/Entity.cpp
src/pubsub/Network.cpp
src/pubsub/NetworkDevice.cpp

Add option for delay in simulated network comms using comm_delay argument in network definition (see missions/delay-test.xml. Stochastic delay can be implemented in user-defined network plugin but may cause significant slowdown of the simulation.

Delay comms

---

include/scrimmage/plugins/autonomy/SimpleINS/SimpleINS.h
include/scrimmage/plugins/interaction/Boundary/Plane.h
include/scrimmage/plugins/sensor/GPS/GPS.h
include/scrimmage/plugins/sensor/GPS/GPS.xml
msgs/GPS.proto
src/plugins/autonomy/SimpleINS/CMakeLists.txt
src/plugins/autonomy/SimpleINS/SimpleINS.cpp
src/plugins/interaction/Boundary/Boundary.cpp
src/plugins/sensor/GPS/CMakeLists.txt
src/plugins/sensor/GPS/GPS.cpp

- Added GPS sensor plugin which will help simulate GPS by providing information such as: Lat/Lon/Alt, time, whether gps fix is enabled/disabled. 
- Added Plane.h which informs user whether an entity is below the plane within its enclosed region.
- Added SimpleINS autonomy plugin which calculates a covariance in order to publish on the StateWithCovariance topic. Very simplistic INS model.

Added GPS sensor and SimpleINS autonomy plugin

---

docs/source/tutorials/openai-plugin.rst
include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.h
include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.xml
python/scrimmage/openai_grpc_link.py
src/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.cpp
test/test_openai.cpp
test/test_openai.py

Also fixes various bugs in the grpc non-learning mode

Add grpc non-learning mode documentation and tests

---

include/scrimmage/plugins/autonomy/AutonomyExecutor/AutonomyExecutor.h
include/scrimmage/plugins/autonomy/GoToWaypoint/GoToWaypoint.h
include/scrimmage/plugins/autonomy/GoToWaypoint/GoToWaypoint.xml
src/plugins/autonomy/AutonomyExecutor/AutonomyExecutor.cpp
src/plugins/autonomy/GoToWaypoint/CMakeLists.txt
src/plugins/autonomy/GoToWaypoint/GoToWaypoint.cpp

- GoToWaypoint allows the user to either specified a location they want to go to or use current location.
- AutonomyExecutor has been updated to restart init when switching autonomy states.

Added GoToWaypoint autonomy & updated AutonomyExecutor to restart init

---

README.md

Documentation updates.

---

CMakeLists.txt

https://stackoverflow.com/a/44635686

add compatibility for vtk

---

src/plugins/motion/Unicycle/Unicycle.cpp

the viewed roll was in the wrong direction

fix roll calculation in Unicycle.h

---

include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/OpenAIObservations.h
include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.h
python/scrimmage/bindings/src/py_openai_env.cpp
python/scrimmage/bindings/src/py_openai_env.h
src/plugins/autonomy/ScrimmageOpenAIAutonomy/OpenAIObservations.cpp
src/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.cpp

Allows the OpenAI interface to handle agents to come in and out of the simulation

Add dynamic OpenAI interface state space

---

CMakeLists.txt
src/simcontrol/SimControl.cpp

- link to opencv libraries properly in exported target

add sleep() for pause efficiency

---

docs/source/tutorials/controller-plugin.rst

Updated tutorial documentation to reflect use of VariableIO in SimpleAircraftControllerPID.

Updated tutorial documentation

---

docs/source/overview/logging.rst

There were missing commas in the append block.

fixed CSV logging documentation

---

ci/dockerfiles/ubuntu-16.04

travis was previously failing because scipy 1.3.0 no longer supports
python2.

update docker to use python3

---

3rd-party/README.md

Break it up into paragraphs so it is easier to scan over & use code
formatting where appropriate.

Improve 3rd-party/readme

---

docs/source/tutorials/airsim-plugin.rst
include/scrimmage/plugins/sensor/AirSimSensor/AirSimSensor.h
missions/quad-airsim-ex1.xml
src/plugins/autonomy/Straight/Straight.cpp
src/plugins/motion/Multirotor/Multirotor.cpp
src/plugins/sensor/AirSimSensor/AirSimSensor.cpp

Edits and tutorial for setting up AirSim v1.1.8/Unreal Engine 4.18 on Windows machine and scrimmage on Linux machine on same network for scrimmage's AirSimSensor plugin.

Scrimmage Edits for building AirSim on Windows/Linux Setup 

---

docs/source/tutorials/airsim-plugin.rst

Added instructions for using AirSim's Asset environments and fixed typos.

Added instructions for using AirSim's Asset environments and fixed typos.

---

include/scrimmage/plugins/sensor/RayTrace/RayTrace.h
src/plugins/interaction/BulletCollision/BulletCollision.cpp
src/viewer/Updater.cpp

Added ability to do ray tracing based on a sensor that provides data in world coordinates instead of sensor coordinates.

Point cloud updates

---

docs/source/tutorials/optimize.rst
missions/predator_prey_boids.xml
scripts/optimization_tutorial.py
scripts/run_experiments.py

Update the tutorials to work with the latest master version of Scrimmage.

Update Tutorials Optimizing Parameters & Multiple Runs

---

src/plugins/autonomy/ROSAutonomy/ROSAutonomy.cpp

this is a bandaid, open to suggestions for the proper fix

remove broken class member calls in rosautonomy

---

include/scrimmage/plugins/motion/JSBSimControl/JSBSimControl.xml
include/scrimmage/plugins/motion/JSBSimModel/JSBSimModel.xml
src/plugins/motion/JSBSimControl/JSBSimControl.cpp
src/plugins/motion/JSBSimModel/JSBSimModel.cpp

Added to JSBSimControl and JSBSimModel motion models

Add option to override JSBSim Root location

---

docs/source/tutorials/autonomy-plugin.rst

A new user test to 1) try and make a (small, but) meaningful contribution to the documentation and 2) verify correct steps were taken to adhere to the update process required my @SyllogismRXS. It wasn't actual code, so I didn't run the cpplint, cppcheck, and static code tests (hope that's ok). In the future, I won't submit for such a small change and will try to group updates in a larger batch. Let me know if this works for the project. Thanks!
Lonnie

Grammatical update in Autonomy plug-in

---

CMakeLists.txt
README.md
ci/dockerfiles/ubuntu-16.04
ci/dockerfiles/ubuntu-18.04
docs/source/tutorials/airsim-plugin.rst
include/scrimmage/plugins/autonomy/ROSAirSim/ROSAirSim.h
include/scrimmage/plugins/sensor/AirSimSensor/AirSimSensor.h
include/scrimmage/plugins/sensor/AirSimSensor/AirSimSensor.xml
include/scrimmage/plugins/sensor/AirSimSensor/settings.json
missions/quad-airsim-ex1.xml
src/plugins/autonomy/ROSAirSim/ROSAirSim.cpp
src/plugins/autonomy/Straight/Straight.cpp
src/plugins/sensor/AirSimSensor/AirSimSensor.cpp
src/plugins/sensor/ROSAltimeter/CMakeLists.txt
src/plugins/sensor/ROSIMUSensor/ROSIMUSensor.cpp

Can now have 1 vehicle in AirSim per Entity in Scrimmage.

Use Multiple Vehicles in AirSim

---

include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCameraType.h
src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp

This addition allows the user to simulate a gimballed camera by modifying the camera orientation during runtime.

Update ContactBlobCamera to allow realtime positioning

---

include/scrimmage/plugins/sensor/ROSIMUSensor/ROSIMUSensor.h
missions/quad-airsim-ex1.xml
src/plugins/sensor/ROSIMUSensor/ROSIMUSensor.cpp

Port of an IMU simulator built in MatLab into the RosImuSensor to produce 'ideal' IMU data based on current and previous data frames of an entity. Modify csv data output for usage in other systems.

IMU simulation

---

src/plugins/sensor/ROSAltimeter/CMakeLists.txt

Was affecting effecting William Syre's work so I decided to merge it in now instead of after the cppcheck edits.

Add roscpp to fix linker error

---

include/scrimmage/plugins/sensor/ROSIMUSensor/HG4930IMUBudget.h
include/scrimmage/plugins/sensor/ROSIMUSensor/IMUErrorBudgetTemplate.h
include/scrimmage/plugins/sensor/ROSIMUSensor/IMUErrorSimulator.h
include/scrimmage/plugins/sensor/ROSIMUSensor/ROSIMUSensor.h
src/plugins/sensor/ROSIMUSensor/HG4930IMUBudget.cpp
src/plugins/sensor/ROSIMUSensor/IMUErrorSimulator.cpp
src/plugins/sensor/ROSIMUSensor/ROSIMUSensor.cpp

Added classes converted from Matlab code which generate simulated IMU noise based on a Honeywell HG4930 IMU. Add noise to sensor outputs to ROS and add additional output columns to the output CSV for the ROSIMUSensor

Add Error simulation to ROSIMUSensor

---

include/scrimmage/plugins/motion/RigidBody6DOF/RigidBody6DOFBase.h
include/scrimmage/plugins/motion/RigidBody6DOF/RigidBody6DOFState.h
src/plugins/autonomy/ArduPilot/ArduPilot.cpp
src/plugins/motion/FixedWing6DOF/FixedWing6DOF.cpp
src/plugins/sensor/RigidBody6DOFStateSensor/RigidBody6DOFStateSensor.cpp

I'm getting some hits on the cpplint and cppcheck, but doesn't look like my stuff. Let me know if I need to make changes

added a constant wind model for fixed wing and ardupilot interface

---

docs/source/tutorials/airsim-plugin.rst
missions/quad-airsim-ex1.xml
src/plugins/autonomy/ROSAirSim/ROSAirSim.cpp

Fix could not find plugin ROSAirSim bug, add comments to default AirSim mission, fix typo in docs

Fix could not find plugin ROSAirSim bug

---

include/scrimmage/plugins/motion/FixedWing6DOF/FixedWing6DOF.h
src/plugins/motion/FixedWing6DOF/FixedWing6DOF.cpp

allows external force to be applied and fixes the transport function

allowing an external force in the fixed wing model

---

include/scrimmage/log/Log.h
include/scrimmage/parse/MissionParse.h
missions/straight.xml
src/entity/External.cpp
src/log/Log.cpp
src/parse/MissionParse.cpp
src/simcontrol/SimControl.cpp

All tests passed when running `docker build -f ./ci/dockerfiles/ubuntu-18.04 .`

Add optional parameter in mission files to ignore bin logging

---

include/scrimmage/plugins/autonomy/ArduPilot/ArduPilot.h
src/plugins/autonomy/ArduPilot/ArduPilot.cpp

This merge request allows the ardupilot interface to run synchronously. Additionally it adds some printouts to allow user to monitor timing

adding option to run ardupilot interface sychronously

---

src/common/RTree.cpp
src/plugins/sensor/LOSSensor/LOSSensor.cpp

Simple Patch to fix missing includes when migrating Scrimmage to newer versions of ubuntu.

24.04 Patch

---

include/scrimmage/math/Quaternion.h
src/math/Quaternion.cpp
src/plugins/autonomy/ArduPilot/ArduPilot.cpp
src/plugins/motion/FixedWing6DOF/FixedWing6DOF.cpp
test/test_quaternion.cpp

This request fixes numerical precision issues with converting quaternions to roll pitch yaw in the model.

FixedWing6DOF: more robust rotation handling
